### ISSUE TITLE
Extra Points

### ISSUE THREAD

**Issue by RauschSchottManuel** [Teaching-HTL-Leonding/robot-maze-quiz-RauschSchottManuel#1]
@rstropek I created one extra unit test as stated in the readme therefore i think i deserve an extra point

**Comment by rstropek** [comment]
You get it. Just two comments:

* **Avoid** checking in binaries (e.g. dll, pdb)
* In practice, **consider** https://github.com/dotnet/BenchmarkDotNet for creating benchmarks
